[build]
  command = "echo 'No build step needed'"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://budgetgm-backend.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600" 